[package]
name = "lucy-svelte"
version = "1.0.0"
description = "Lucy SysAdmin Assistant"
authors = ["Edd Luna"]
edition = "2021"

[lib]
name = "lucy_svelte_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri      = { version = "2.0.0", features = [] }
serde      = { version = "1",     features = ["derive"] }
serde_json = "1"
reqwest    = { version = "0.12",  features = ["json", "stream"] }
futures-util = "0.3"
base64     = "0.22"
rfd        = "0.14"
sysinfo    = "0.30"
keyring    = "2.3"
chrono     = "0.4"
once_cell  = "1"
tokio      = { version = "1", features = ["time", "rt"] }
winreg     = "0.52"
git2       = "0.18" # Para control de versiones y rollback automático
tauri-plugin-sql = { version = "2.0.0", features = ["sqlite"] }
