// ── predictive-chips.ts — U5 contextual next-action suggestions ──────────
//
// Looks at the LAST Lucy turn (message + tool cards + errors) and proposes
// 1-3 short chips representing likely next actions.
//
// Design:
//   • Pure heuristic — no LLM call. Fast (< 1ms), predictable, debuggable.
//   • Each ChipRule declares the conversation domains it belongs to.
//     detectDomain() classifies the current turn; rules outside the detected
//     domain are skipped. This prevents sysadmin chips during image analysis, etc.
//   • Engagement scoring: clicks and dismisses are persisted to localStorage.
//     Chips the user actually uses rise to the top; ignored chips sink.
//   • Output is plain data — UI renders it.

export interface PredictiveChip {
    id:       string;
    label:    string;
    tooltip:  string;
    icon:     string;
    action:
        | { kind: 'fill_input'; text: string }
        | { kind: 'run_command'; cmd: string }
        | { kind: 'slash'; command: string };
    severity?: 'info' | 'suggest' | 'caution';
    /**
     * Provenance — where this chip came from. Drives the small badge
     * rendered in the strip so users build trust in the suggestions
     * (Claude Desktop-style "why am I seeing this").
     *   - 'heuristic' : pattern-matched on the last turn (instant, sync)
     *   - 'llm'       : generated by a tiny background LLM call (async)
     *   - 'memory'    : learned from past sessions / engagement stats
     */
    source?: 'heuristic' | 'llm' | 'memory';
}

/** Raw chip returned by the backend `generate_smart_chips` Tauri command. */
export interface BackendSmartChip {
    label:     string;
    text:      string;
    intent:    'diagnose' | 'verify' | 'explain' | 'fix' | 'export' | 'continue' | 'other';
    rationale: string;
}

/**
 * Map a backend LLM-generated chip into the unified PredictiveChip shape.
 * Picks an icon and severity from the `intent` so colors stay consistent
 * with the heuristic chips. The id is salted with the label so dismissing
 * a specific LLM-generated chip in this turn actually hides THAT chip
 * (different turns produce different chips, so we don't dedupe across).
 */
export function backendChipToPredictive(c: BackendSmartChip, idx: number): PredictiveChip {
    const ICON: Record<string, string> = {
        diagnose: '△', verify: '✓', explain: '?', fix: '🛠',
        export: '⇪', continue: '→', other: '✦',
    };
    const SEV: Record<string, 'info' | 'suggest' | 'caution'> = {
        diagnose: 'caution', verify: 'suggest', explain: 'info',
        fix: 'caution', export: 'info', continue: 'suggest', other: 'info',
    };
    // Stable id based on label so click stats can accumulate across turns
    // when the LLM happens to produce the same label (e.g. "Continue").
    const slug = c.label.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 24);
    return {
        id:      `llm-${slug}-${idx}`,
        label:   c.label,
        tooltip: c.rationale || c.text,
        icon:    ICON[c.intent] || '✦',
        action:  { kind: 'fill_input', text: c.text },
        severity: SEV[c.intent] || 'info',
        source:  'llm',
    };
}

/**
 * Merge heuristic + LLM + memory chips into a final 3-slot list.
 *
 * Strategy: alternate sources so the user always sees variety instead of
 * "3 heuristic chips OR 3 LLM chips". Concretely:
 *   slot 0 → best LLM chip (if any), else best heuristic
 *   slot 1 → best heuristic that isn't a near-duplicate of slot 0
 *   slot 2 → second-best LLM, else second-best heuristic
 *
 * Dedup: two chips are "near-duplicates" if their lowercased labels share
 * a 4+ char substring. Cheap and catches "Continue" vs "Continue investigation".
 */
export function mergeChips(
    heuristics: PredictiveChip[],
    llmChips:   PredictiveChip[],
): PredictiveChip[] {
    const merged: PredictiveChip[] = [];
    const used = new Set<string>();
    const isDup = (c: PredictiveChip) => {
        const a = c.label.toLowerCase();
        return merged.some(m => {
            const b = m.label.toLowerCase();
            if (a === b) return true;
            // Shared 4+ char substring → likely paraphrase.
            for (let i = 0; i <= a.length - 4; i++) {
                if (b.includes(a.substring(i, i + 4))) return true;
            }
            return false;
        });
    };
    const push = (c: PredictiveChip | undefined) => {
        if (!c || used.has(c.id) || isDup(c)) return;
        used.add(c.id);
        merged.push(c);
    };

    // Interleave LLM → heuristic → LLM → heuristic until we hit 3.
    let li = 0, hi = 0;
    while (merged.length < 3 && (li < llmChips.length || hi < heuristics.length)) {
        if (li < llmChips.length)   push(llmChips[li++]);
        if (merged.length >= 3) break;
        if (hi < heuristics.length) push(heuristics[hi++]);
    }
    return merged;
}

export interface ChipContext {
    lastLucyText:  string;
    lastUserText:  string;
    hadTools:      boolean;
    toolLabels:    string[];
    hadError:      boolean;
    hasOpenQuestion: boolean;
    cwd?:          string;
    /** Detected conversation domains — computed by detectDomain(). */
    domains:       Set<string>;
}

type ChipRule = {
    name: string;
    /**
     * Which conversation domains this chip belongs to.
     * A chip only fires if at least one of its domains is in ctx.domains.
     * Use ['general'] or omit for chips that should always be candidates.
     */
    domains: string[];
    matches: (ctx: ChipContext) => boolean;
    build:   (ctx: ChipContext) => PredictiveChip | null;
};

// ── Domain detection ─────────────────────────────────────────────────────
// Cheap keyword scan over the combined turn text. Returns a Set of active
// domain tags. 'general' is always present.

export function detectDomain(userText: string, lucyText: string): Set<string> {
    const t = (userText + ' ' + lucyText).toLowerCase();
    const d = new Set<string>(['general']);

    if (/cpu|ram|memoria|process|servicio|service|disco|disk|log|server|ping|red|network|sudo|systemctl|journald|firewall|puerto|port|daemon|cron|dnf|apt|yum|bash|shell|ssh|sftp/.test(t))
        d.add('sysadmin');

    if (/git|commit|branch|diff|código|function|bug|refactor|\.ts|\.py|\.rs|\.js|\.go|import|export|const|class|método|method|variable|repositorio|repo|build|test|linting/.test(t))
        d.add('code');

    if (/imagen|foto|photo|jpg|jpeg|png|gif|webp|svg|midjourney|stable.diffusion|ia.generativa|artefacto|fondo|render|pixel|resolución|ilustración|generada.por/.test(t))
        d.add('image');

    if (/lent[oa]|slow|tard[óo]|spike|congestión|congestion|alto.*cpu|cpu.*alto|lag|freeze|hang|bloqueado|blocking|timeout|latencia|latency/.test(t))
        d.add('perf');

    if (/incidente|incident|anomal|alerta|alert|degradad|outage|caída|down|p[0-9]\b|sev[0-9]\b/.test(t))
        d.add('incident');

    if (/archivo|file|carpeta|folder|directorio|directory|leer|escribir|crear|borrar|mover|copiar|read.*file|write.*file|new-item|remove-item/.test(t))
        d.add('file');

    if (/resumen|resumir|summary|resume|tl.?dr|sintetiz|simplifica|explica.en.pocas/.test(t))
        d.add('summarize');

    return d;
}

// ── Pattern library ──────────────────────────────────────────────────────

const RULES: ChipRule[] = [
    {
        name: 'analyze-after-read',
        domains: ['code', 'file'],
        matches: (c) => c.hadTools && c.toolLabels.some(l => /readfile|read.?file|abrir|open/.test(l)),
        build: () => ({
            id: 'chip-analyze',
            label: 'Analiza este código',
            tooltip: 'Pide a Lucy un resumen técnico + posibles bugs del último archivo abierto',
            icon: '⌬',
            action: { kind: 'fill_input', text: 'Analiza este código que acabamos de leer: ¿qué hace, qué riesgos tiene, qué optimizarías?' },
            severity: 'info',
        }),
    },

    {
        name: 'healing-after-error',
        domains: ['sysadmin', 'code', 'general'],
        matches: (c) => c.hadError || /error|failed|no such|denied|exception|rechazado|fallo/i.test(c.lastLucyText),
        build: (c) => {
            const m = c.lastLucyText.match(/error[:\s]+([^.\n]{8,80})/i);
            const symptom = m ? m[1].trim() : 'error reciente';
            return {
                id: 'chip-healing',
                label: '¿Lo he resuelto antes?',
                tooltip: 'Busca en la memoria de Lucy fixes previos a un error parecido',
                icon: '💊',
                action: { kind: 'fill_input', text: `Busca en tu memoria si ya he resuelto algo parecido a: "${symptom}". Usa <TOOL>healing_find:${symptom}</TOOL>.` },
                severity: 'caution',
            };
        },
    },

    {
        name: 'snapshot-after-status',
        domains: ['sysadmin', 'perf'],
        matches: (c) => /CPU|RAM|memoria|process|servicio|service|disco|disk/i.test(c.lastLucyText)
                     && !c.toolLabels.some(l => l.includes('snapshot')),
        build: () => ({
            id: 'chip-snapshot',
            label: 'Capturar snapshot',
            tooltip: 'Guarda el estado actual del sistema para comparar más tarde (/snapshot)',
            icon: '◫',
            action: { kind: 'slash', command: '/snapshot' },
            severity: 'suggest',
        }),
    },

    {
        name: 'diagnose-after-slow',
        domains: ['perf', 'sysadmin'],
        matches: (c) => c.domains.has('perf'),
        build: () => ({
            id: 'chip-diagnose',
            label: '¿Por qué se puso lenta?',
            tooltip: 'Correlaciona procesos recientes con el síntoma (F3 Causal Engine)',
            icon: '△',
            action: { kind: 'fill_input', text: '¿Por qué se puso lenta mi máquina hace un momento? Usa <TOOL>diagnose_spike:300</TOOL> para investigar.' },
            severity: 'suggest',
        }),
    },

    {
        name: 'commit-after-git',
        domains: ['code'],
        matches: (c) => /git\s+status|git\s+diff|sin commitear|uncommitted/i.test(c.lastLucyText),
        build: () => ({
            id: 'chip-git-commit',
            label: 'Generar commit',
            tooltip: 'Crea un commit message convencional a partir del diff actual',
            icon: '⌥',
            action: { kind: 'fill_input', text: 'Genera un mensaje de commit convencional para los cambios actuales y muéstrame el comando.' },
            severity: 'info',
        }),
    },

    {
        name: 'confirm-plan',
        domains: ['sysadmin', 'code', 'general'],
        matches: (c) => /<PLAN>|plan propuesto|paso 1|step 1|primero,/i.test(c.lastLucyText)
                     && !c.lastLucyText.includes('CONFIRMADO'),
        build: () => ({
            id: 'chip-confirm',
            label: 'Procede con el plan',
            tooltip: 'Confirma el plan y deja que Lucy ejecute los pasos',
            icon: '▶',
            action: { kind: 'fill_input', text: 'Confirmado, procede con el plan.' },
            severity: 'suggest',
        }),
    },

    {
        name: 'investigate-incident',
        domains: ['incident', 'sysadmin'],
        matches: (c) => c.domains.has('incident') && c.hasOpenQuestion,
        build: () => ({
            id: 'chip-state-diff',
            label: '¿Qué cambió?',
            tooltip: 'Compara el estado actual con el snapshot de hace 30 min',
            icon: '◐',
            action: { kind: 'fill_input', text: '¿Qué cambió en mi máquina en los últimos 30 minutos? Usa <TOOL>state_diff:30</TOOL>.' },
            severity: 'caution',
        }),
    },

    {
        name: 'summarize-long',
        // Only offer "summarize" for technical/sysadmin content — not for image analysis
        // or general chit-chat where a TL;DR adds no value.
        domains: ['sysadmin', 'code', 'incident', 'perf', 'file'],
        matches: (c) => c.lastLucyText.length > 1600,
        build: () => ({
            id: 'chip-summary',
            label: 'Resúmeme esto',
            tooltip: 'Pide un TL;DR de 3 líneas de la última respuesta',
            icon: '☱',
            action: { kind: 'fill_input', text: 'Resúmeme la respuesta anterior en 3 líneas máximo, sólo lo esencial.' },
            severity: 'info',
        }),
    },

    // ── New domain-aware chips ───────────────────────────────────────────

    {
        name: 'image-detect-ai',
        domains: ['image'],
        matches: (c) => /generada|generated|midjourney|stable.diffusion|ia|ai.art|artefacto/i.test(c.lastLucyText),
        build: () => ({
            id: 'chip-image-ai',
            label: 'Detectar más artefactos',
            tooltip: 'Pide un análisis más profundo de marcadores de IA en la imagen',
            icon: '🔍',
            action: { kind: 'fill_input', text: 'Dame un análisis más detallado de los artefactos típicos de IA generativa que puedas detectar en esta imagen.' },
            severity: 'info',
        }),
    },

    {
        name: 'image-save-analysis',
        domains: ['image'],
        matches: (c) => c.lastLucyText.length > 400,
        build: () => ({
            id: 'chip-image-save',
            label: 'Guardar análisis',
            tooltip: 'Exporta el análisis de la imagen como archivo de texto',
            icon: '⊞',
            action: { kind: 'fill_input', text: 'Guarda el análisis anterior como un archivo .txt en el escritorio con un nombre descriptivo.' },
            severity: 'suggest',
        }),
    },

    {
        name: 'open-question-followup',
        domains: ['sysadmin', 'code', 'incident'],
        matches: (c) => c.hasOpenQuestion && !c.hadError,
        build: () => ({
            id: 'chip-followup',
            label: 'Continuar investigación',
            tooltip: 'Lucy tiene una pregunta abierta — continuar desde donde quedamos',
            icon: '→',
            action: { kind: 'fill_input', text: 'Continúa con la investigación que dejaste pendiente.' },
            severity: 'suggest',
        }),
    },

    {
        name: 'file-cleanup',
        domains: ['file'],
        matches: (c) => /temp|tmp|basura|trash|cache|log.*viejo|old.*log|cleanup/i.test(c.lastLucyText),
        build: () => ({
            id: 'chip-cleanup',
            label: 'Limpiar archivos temporales',
            tooltip: 'Elimina archivos temporales y caché mencionados',
            icon: '🧹',
            action: { kind: 'fill_input', text: 'Limpia los archivos temporales y caché que mencionaste, con confirmación antes de borrar.' },
            severity: 'suggest',
        }),
    },
];

// ── Engagement scoring ───────────────────────────────────────────────────
// Persisted to localStorage so Lucy learns which chips the user actually uses.

const STATS_KEY = 'lucy_chip_stats';

interface ChipStats { clicks: number; dismisses: number; }

function _loadStats(): Record<string, ChipStats> {
    try {
        return JSON.parse(localStorage.getItem(STATS_KEY) || '{}');
    } catch { return {}; }
}
function _saveStats(s: Record<string, ChipStats>): void {
    try { localStorage.setItem(STATS_KEY, JSON.stringify(s)); } catch {}
}

export function recordChipClick(id: string): void {
    const s = _loadStats();
    if (!s[id]) s[id] = { clicks: 0, dismisses: 0 };
    s[id].clicks++;
    _saveStats(s);
}

export function recordChipDismiss(id: string): void {
    const s = _loadStats();
    if (!s[id]) s[id] = { clicks: 0, dismisses: 0 };
    s[id].dismisses++;
    _saveStats(s);
}

/** Higher = show first. Chips the user clicks rise; chips they dismiss sink. */
function _engagementScore(id: string, stats: Record<string, ChipStats>): number {
    const st = stats[id];
    if (!st) return 0;
    return st.clicks - st.dismisses * 0.6;
}

// ── Main export ──────────────────────────────────────────────────────────

export function predictChips(ctx: ChipContext): PredictiveChip[] {
    const stats = _loadStats();
    const out: PredictiveChip[] = [];
    const seen = new Set<string>();

    // Collect all matching chips (domain-filtered)
    const candidates: Array<{ chip: PredictiveChip; score: number }> = [];

    for (const rule of RULES) {
        try {
            // Domain gate: rule must share at least one domain with the detected domains.
            const ruleDomains = rule.domains.length ? rule.domains : ['general'];
            const domainMatch = ruleDomains.some(d => ctx.domains.has(d));
            if (!domainMatch) continue;

            if (!rule.matches(ctx)) continue;
            const chip = rule.build(ctx);
            if (!chip || seen.has(chip.id)) continue;
            seen.add(chip.id);
            candidates.push({ chip, score: _engagementScore(chip.id, stats) });
        } catch {
            continue;
        }
    }

    // Sort by engagement score desc — chips the user uses most float to top.
    // Ties preserve rule declaration order (stable sort).
    candidates.sort((a, b) => b.score - a.score);

    for (const { chip } of candidates) {
        // Heuristics get tagged at the boundary instead of inside every
        // rule's build() — keeps the rule library compact.
        out.push({ ...chip, source: chip.source ?? 'heuristic' });
        if (out.length >= 3) break;
    }
    return out;
}

// ── Dismiss memory (per-turn sticky) ─────────────────────────────────────

const _dismissed = new Set<string>();

export function dismissChip(id: string): void { _dismissed.add(id); }
export function isDismissed(id: string): boolean { return _dismissed.has(id); }
export function resetDismissed(): void { _dismissed.clear(); }
