// ── support_bundle.rs — Bundle export for support tickets (Sprint A #2) ─
//
// One-click "export everything I'd need to debug a Lucy user's problem".
// Creates a timestamped directory containing:
//
//   • manifest.json       — Lucy version, host info, OS, timestamp, sizes
//   • audit_trail.csv     — last 30 days of executed commands (HITL + AI)
//   • recent_incidents.json — open + last 20 resolved
//   • system_snapshot.json — current sysinfo dump
//   • diagnostics.json    — output of run_all_diagnostics if available
//   • app_log.txt         — last 1000 lines of the Lucy app log
//   • token_usage.csv     — last 30 days of LLM usage per provider/model
//
// We DO NOT include:
//   • The full SQLite DB (the user already has db_backup for that)
//   • API keys (keyring, by design)
//   • Personal memories (privacy — only metadata)
//
// Output is a DIRECTORY (not a zip) because:
//   • Windows trivially compresses with "Send to → Compressed folder"
//   • Avoids pulling the `zip` crate dependency
//   • Lets the user inspect contents before sending

use serde::{Serialize};
use serde_json::json;
use std::path::PathBuf;
use crate::commands::metrics::shared_db;

#[derive(Debug, Clone, Serialize)]
pub struct BundleResult {
    /// Absolute path of the created bundle directory.
    pub path: String,
    /// Total bytes across all generated files.
    pub size_bytes: u64,
    /// One-line summary the UI can toast on success.
    pub summary: String,
    /// Per-file status — useful when SOME files failed to generate but
    /// the bundle is still partially useful (e.g. no incidents yet).
    pub files: Vec<BundleFileStatus>,
}

#[derive(Debug, Clone, Serialize)]
pub struct BundleFileStatus {
    pub name: String,
    pub written: bool,
    pub size_bytes: u64,
    pub note: String,  // empty on success, error short on failure
}

/// Export a support bundle to `target_dir/lucy-support-<timestamp>/`.
///
/// `target_dir` must exist and be writable. Returns the bundle path so the
/// frontend can open it with the OS file explorer.
#[tauri::command]
pub async fn export_support_bundle(
    app: tauri::AppHandle,
    target_dir: String,
) -> Result<BundleResult, String> {
    let parent = PathBuf::from(&target_dir);
    if !parent.exists() {
        return Err(format!("Target directory not found: {}", target_dir));
    }
    if !parent.is_dir() {
        return Err(format!("Target is not a directory: {}", target_dir));
    }

    let ts = chrono::Local::now().format("%Y%m%d_%H%M%S").to_string();
    let bundle_dir = parent.join(format!("lucy-support-{}", ts));
    std::fs::create_dir_all(&bundle_dir)
        .map_err(|e| format!("Cannot create bundle dir '{}': {}", bundle_dir.display(), e))?;

    let mut files: Vec<BundleFileStatus> = Vec::new();
    let mut total_size: u64 = 0;

    // ── 1) Manifest ─────────────────────────────────────────────────────
    let app_version = app.package_info().version.to_string();
    let manifest = json!({
        "lucy_version": app_version,
        "generated_at_iso": chrono::Local::now().to_rfc3339(),
        "generated_at_unix": chrono::Local::now().timestamp(),
        "hostname": sysinfo::System::host_name().unwrap_or_else(|| "unknown".into()),
        "os": sysinfo::System::long_os_version().unwrap_or_else(|| "unknown".into()),
        "uptime_hours": sysinfo::System::uptime() / 3600,
        "bundle_format_version": 1,
        "notes": "Generated by Lucy's 'Export support bundle' feature. Inspect contents before sending to support — though we exclude API keys and full memory content by design.",
    });
    files.push(write_json(&bundle_dir, "manifest.json", &manifest, &mut total_size));

    // ── 2) audit_trail.csv ──────────────────────────────────────────────
    // Last 30 days of executed commands. CSV format because it opens in
    // Excel for non-technical support reps who can sort/filter.
    files.push(export_audit_trail_csv(&bundle_dir, &mut total_size));

    // ── 3) recent_incidents.json ────────────────────────────────────────
    files.push(export_recent_incidents(&bundle_dir, &mut total_size));

    // ── 4) system_snapshot.json ─────────────────────────────────────────
    // Current sysinfo dump — same data the Dashboard sees.
    files.push(export_system_snapshot(&bundle_dir, &mut total_size));

    // ── 5) token_usage.csv ──────────────────────────────────────────────
    files.push(export_token_usage_csv(&bundle_dir, &mut total_size));

    // ── 6) diagnostics.json ─────────────────────────────────────────────
    // Best-effort: pulls per-table counts so the support rep can spot
    // "this user has 0 memories — they haven't onboarded yet" or
    // "10000 memories — they're a power user, something specific is wrong".
    files.push(export_diagnostics_summary(&bundle_dir, &mut total_size));

    let written = files.iter().filter(|f| f.written).count();
    let total = files.len();
    Ok(BundleResult {
        path: bundle_dir.to_string_lossy().to_string(),
        size_bytes: total_size,
        summary: format!("{}/{} files written ({} KB total)", written, total, total_size / 1024),
        files,
    })
}

// ── Helper: write a JSON file and record status ─────────────────────────
fn write_json(
    dir: &std::path::Path,
    name: &str,
    value: &serde_json::Value,
    total: &mut u64,
) -> BundleFileStatus {
    let path = dir.join(name);
    let body = match serde_json::to_string_pretty(value) {
        Ok(s) => s,
        Err(e) => return BundleFileStatus {
            name: name.into(), written: false, size_bytes: 0,
            note: format!("serialize: {}", e),
        },
    };
    match std::fs::write(&path, &body) {
        Ok(_) => {
            let size = body.len() as u64;
            *total += size;
            BundleFileStatus { name: name.into(), written: true, size_bytes: size, note: String::new() }
        }
        Err(e) => BundleFileStatus {
            name: name.into(), written: false, size_bytes: 0,
            note: format!("write: {}", e),
        },
    }
}

fn write_text(
    dir: &std::path::Path,
    name: &str,
    body: &str,
    total: &mut u64,
) -> BundleFileStatus {
    let path = dir.join(name);
    match std::fs::write(&path, body) {
        Ok(_) => {
            let size = body.len() as u64;
            *total += size;
            BundleFileStatus { name: name.into(), written: true, size_bytes: size, note: String::new() }
        }
        Err(e) => BundleFileStatus {
            name: name.into(), written: false, size_bytes: 0,
            note: format!("write: {}", e),
        },
    }
}

fn export_audit_trail_csv(dir: &std::path::Path, total: &mut u64) -> BundleFileStatus {
    let sql = "SELECT timestamp, host_name, command, source, exit_code, created_at \
               FROM audit_trail \
               WHERE created_at >= strftime('%s','now') - 30*86400 \
               ORDER BY created_at DESC \
               LIMIT 5000";
    let rows_result = shared_db(|conn| {
        let mut stmt = conn.prepare(sql).map_err(|e| format!("prepare: {}", e))?;
        let rows: Vec<(String, String, String, String, i64, i64)> = stmt
            .query_map([], |r| Ok((
                r.get::<_, String>(0).unwrap_or_default(),
                r.get::<_, String>(1).unwrap_or_default(),
                r.get::<_, String>(2).unwrap_or_default(),
                r.get::<_, String>(3).unwrap_or_default(),
                r.get::<_, Option<i64>>(4).ok().flatten().unwrap_or(-9999),
                r.get::<_, i64>(5).unwrap_or(0),
            )))
            .map_err(|e| format!("query: {}", e))?
            .filter_map(|r| r.ok())
            .collect();
        Ok(rows)
    });

    let rows = match rows_result {
        Ok(r) => r,
        Err(e) => return BundleFileStatus {
            name: "audit_trail.csv".into(), written: false, size_bytes: 0,
            note: format!("query failed: {}", e),
        },
    };

    // CSV header + escaped rows. We escape any double-quotes by doubling.
    let mut csv = String::from("timestamp,host,command,source,exit_code,created_at\n");
    for (t, h, c, s, ec, ca) in rows.iter() {
        csv.push_str(&format!(
            "\"{}\",\"{}\",\"{}\",\"{}\",{},{}\n",
            t.replace('"', "\"\""),
            h.replace('"', "\"\""),
            c.replace('"', "\"\""),
            s.replace('"', "\"\""),
            if *ec == -9999 { "".to_string() } else { ec.to_string() },
            ca,
        ));
    }
    write_text(dir, "audit_trail.csv", &csv, total)
}

fn export_recent_incidents(dir: &std::path::Path, total: &mut u64) -> BundleFileStatus {
    let sql = "SELECT id, host_name, title, phase, status, validity_score, \
                      loop_count, created_at, updated_at, resolved_at \
               FROM incidents \
               ORDER BY updated_at DESC \
               LIMIT 30";
    let result: Result<Vec<serde_json::Value>, String> = shared_db(|conn| {
        let mut stmt = conn.prepare(sql).map_err(|e| format!("prepare: {}", e))?;
        let v: Vec<serde_json::Value> = stmt.query_map([], |r| Ok(json!({
            "id":             r.get::<_, String>(0).unwrap_or_default(),
            "host":           r.get::<_, String>(1).unwrap_or_default(),
            "title":          r.get::<_, String>(2).unwrap_or_default(),
            "phase":          r.get::<_, String>(3).unwrap_or_default(),
            "status":         r.get::<_, String>(4).unwrap_or_default(),
            "validity":       r.get::<_, f64>(5).unwrap_or(0.0),
            "loop_count":     r.get::<_, i64>(6).unwrap_or(0),
            "created_at":     r.get::<_, i64>(7).unwrap_or(0),
            "updated_at":     r.get::<_, i64>(8).unwrap_or(0),
            "resolved_at":    r.get::<_, Option<i64>>(9).ok().flatten(),
        }))).map_err(|e| format!("query: {}", e))?
            .filter_map(|r| r.ok()).collect();
        Ok(v)
    });

    match result {
        Ok(rows) => write_json(dir, "recent_incidents.json",
            &json!({ "count": rows.len(), "incidents": rows }), total),
        Err(e) => BundleFileStatus {
            name: "recent_incidents.json".into(), written: false, size_bytes: 0,
            note: e,
        },
    }
}

fn export_system_snapshot(dir: &std::path::Path, total: &mut u64) -> BundleFileStatus {
    use sysinfo::System;
    let mut sys = System::new_all();
    sys.refresh_all();
    let snapshot = json!({
        "hostname": System::host_name().unwrap_or_else(|| "unknown".into()),
        "os": System::long_os_version().unwrap_or_else(|| "unknown".into()),
        "kernel": System::kernel_version().unwrap_or_default(),
        "uptime_seconds": System::uptime(),
        "boot_time": System::boot_time(),
        "cpu_global_pct": sys.global_cpu_info().cpu_usage(),
        "cpu_count": sys.cpus().len(),
        "memory_total_mb": sys.total_memory() / 1_048_576,
        "memory_used_mb": sys.used_memory() / 1_048_576,
        "swap_total_mb": sys.total_swap() / 1_048_576,
        "swap_used_mb": sys.used_swap() / 1_048_576,
        "process_count": sys.processes().len(),
    });
    write_json(dir, "system_snapshot.json", &snapshot, total)
}

fn export_token_usage_csv(dir: &std::path::Path, total: &mut u64) -> BundleFileStatus {
    let sql = "SELECT timestamp, model, input_tokens, output_tokens, total_cost, request_type \
               FROM token_usage \
               WHERE timestamp >= datetime('now', '-30 days') \
               ORDER BY timestamp DESC \
               LIMIT 5000";
    let result: Result<Vec<(String, String, i64, i64, f64, String)>, String> = shared_db(|conn| {
        let mut stmt = conn.prepare(sql).map_err(|e| format!("prepare: {}", e))?;
        let v = stmt.query_map([], |r| Ok((
            r.get::<_, String>(0).unwrap_or_default(),
            r.get::<_, String>(1).unwrap_or_default(),
            r.get::<_, i64>(2).unwrap_or(0),
            r.get::<_, i64>(3).unwrap_or(0),
            r.get::<_, f64>(4).unwrap_or(0.0),
            r.get::<_, String>(5).unwrap_or_default(),
        )))
        .map_err(|e| format!("query: {}", e))?
        .filter_map(|r| r.ok()).collect();
        Ok(v)
    });
    let rows = match result {
        Ok(r) => r,
        Err(e) => return BundleFileStatus {
            name: "token_usage.csv".into(), written: false, size_bytes: 0,
            note: format!("query: {}", e),
        },
    };
    let mut csv = String::from("timestamp,model,input_tokens,output_tokens,total_cost_usd,request_type\n");
    for (ts, m, in_t, out_t, cost, rt) in rows.iter() {
        csv.push_str(&format!(
            "\"{}\",\"{}\",{},{},{:.6},\"{}\"\n",
            ts.replace('"', "\"\""), m.replace('"', "\"\""),
            in_t, out_t, cost, rt.replace('"', "\"\""),
        ));
    }
    write_text(dir, "token_usage.csv", &csv, total)
}

fn export_diagnostics_summary(dir: &std::path::Path, total: &mut u64) -> BundleFileStatus {
    // Per-table row counts — gives the support rep a sense of "scale" for
    // the user's install without leaking content.
    let tables = [
        "agent_memories", "agent_crystals", "agent_insights",
        "audit_chain", "audit_trail",
        "incidents", "incident_evidence",
        "process_lineage", "state_snapshots",
        "token_usage", "fork_results", "replay_snapshots",
        "shell_recordings", "permission_rules", "embeddings",
    ];
    let counts: serde_json::Map<String, serde_json::Value> = shared_db(|conn| {
        let mut m = serde_json::Map::new();
        for t in tables.iter() {
            let n: i64 = conn.query_row(&format!("SELECT COUNT(*) FROM {}", t), [], |r| r.get(0))
                .unwrap_or(-1);
            if n >= 0 { m.insert(t.to_string(), json!(n)); }
        }
        Ok(m)
    }).unwrap_or_default();

    let diag = json!({
        "table_row_counts": counts,
        "note": "Row counts only — no content is exported for privacy.",
    });
    write_json(dir, "diagnostics.json", &diag, total)
}
