// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Una memoria de largo plazo — misma forma que la fila `agent_memories`.
 *
 * LA definición, no una de dos: `src-tauri` la reexporta desde aquí. Existía
 * duplicada campo por campo, y una struct copiada es una struct que acaba
 * difiriendo en una columna que alguien añadió a un lado.
 *
 * El derive de ts-rs va tras la feature `ts` porque exportar TypeScript es un
 * problema de la app Tauri (sus tipos cruzan el puente IPC). El shell nativo
 * llama funciones Rust directamente y no debe compilar ts-rs por compartir un
 * tipo. La ruta de exportación resuelve al mismo `src/lib/types/` desde
 * cualquiera de los dos crates.
 */
export type AgentMemory = { id: bigint, session_id: string, title: string, content: string, tags: string, files: string, importance: bigint, created_at: bigint, };
