// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentMemory = { id: bigint, session_id: string, title: string, content: string, tags: string, files: string, importance: bigint, created_at: bigint, };
