// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventEntry = { time: string, level: string, source: string, event_id: string, message: string, };
