// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Demo of the ts-rs binding pattern (F3.2 of the bridge audit).
 *
 * Adding `#[derive(ts_rs::TS)]` + `#[ts(export, export_to = "...")]` causes
 * `cargo test export_bindings_taskentry` to write a typed `.ts` file to
 * `src/lib/types/`. Frontend then imports the type via:
 *
 * ```ts
 * import type { TaskEntry } from '$lib/types/TaskEntry';
 * const tasks = await invokeTyped<TaskEntry[]>('get_tasklist');
 * ```
 *
 * To apply this to every Tauri-returned struct, repeat the derive pattern.
 * The `chrono-impl` ts-rs feature handles DateTime fields automatically.
 */
export type TaskEntry = { name: string, pid: number, session: string, mem_kb: bigint, };
